-- MySQL Script generated by MySQL Workbench
-- 06/12/19 23:55:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Contactos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Contactos` ;

-- -----------------------------------------------------
-- Schema Contactos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Contactos` DEFAULT CHARACTER SET utf8 ;
USE `Contactos` ;

-- -----------------------------------------------------
-- Table `Contactos`.`Contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contactos`.`Contactos` ;

CREATE TABLE IF NOT EXISTS `Contactos`.`Contactos` (
  `nombre` VARCHAR(24) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telCel` VARCHAR(10) NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Contactos`.`Contactos`
-- -----------------------------------------------------
START TRANSACTION;
USE `Contactos`;
INSERT INTO `Contactos`.`Contactos` (`nombre`, `apellido`, `email`, `telCel`) VALUES ('Allan', 'Poe', 'allan_poe_09@email.com', '4435679083');
INSERT INTO `Contactos`.`Contactos` (`nombre`, `apellido`, `email`, `telCel`) VALUES ('Clive S.', 'Lewis', 'cs_lewis_98@email.com', '4437094524');
INSERT INTO `Contactos`.`Contactos` (`nombre`, `apellido`, `email`, `telCel`) VALUES ('JK', 'Rowling', 'jk_rowling_65@email.com', '4436122456');
INSERT INTO `Contactos`.`Contactos` (`nombre`, `apellido`, `email`, `telCel`) VALUES ('Cassandra', 'Clare', 'cassandra_clare_73@email.com', '4437972345');
INSERT INTO `Contactos`.`Contactos` (`nombre`, `apellido`, `email`, `telCel`) VALUES ('Stephen', 'King', 'stephen_king_47@email.com', '4438996523');

COMMIT;

